version: "3"
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: testtest1000
      MYSQL_DATABASE: nodexlin_db_main
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: testtest1000
      MYSQL_DATABASE: nodexlin_db_main

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: testtest1000
    ports:
      - 8081:80
    depends_on:
      - db